### ISSUE TITLE
The --edit option for transition commands doesn't appear to work

### ISSUE THREAD

**Issue by williamh** [Netflix-Skunkworks/go-jira#101]
Hello again,

For some reason, if I run something like:

```
jira done <issue> --edit
```

then edit the YAML that appears in the editor, the changes I make do not propagate to the ticket, but the client exits successfully. I don't know if this is a template issue or an issue in the code. Can you help with this?

Thanks,

William

**Comment by coryb** [comment]
Hey, this is likely both a template issue and a jira issue.  In many jira projects the transitions do not allow for any field updates, so the existing templates presume you can do things like edit comments, but that is not actually the case for many default project types.

To find out for user you can run `jira transmeta ISSUE-123`, the output should have the `Done` transition and in that transition there should be a `fields` section that indicates what field updates are allowed during transition.  There may not be a `fields` section in the case that no fields are allowed to be updated.

**Comment by coryb** [comment]
I have updated the templates to filter out fields that are not editable during transitions.  By default it looks like most project types do not allow any field updates during transition, so have changed `jira` to at least force a comment update if not allowed during transition, so this will work now:
```
jira done --command "stuff got done" <issue>
```

Not sure if there is anything more we can do here since we are pretty well limited by what the Jira service allows.
