### ISSUE TITLE
Add worklog

### ISSUE THREAD

**Issue by thypon** [Netflix-Skunkworks/go-jira#18]
Add worklog to log done work inside issues.

**Comment by RC1140** [comment]
Have completed this (well a hacked up version for myself , will submit a pull request shortly)

**Comment by coryb** [comment]
I dont have a  place to test worklog logic since we dont use it for the projects that I work on.  @RC1140 any luck on getting that PR working?

**Comment by jameel-cloudafrica** [comment]
Completely forget , will try and get to it this week again.

**Comment by coryb** [comment]
Okay, if you dont have any code already I can probably get to it.  I now have a way to spin-up jira servers at will for testing `go-jira` so I should be able to get this functionality added.

**Comment by jameel-cloudafrica** [comment]
I have the code (its probably doesnt cover every scenario) , main issue is i made a bunch of other changes to the lib (like being able to pass in a user/pass to make my life easier) which I need to rip out.

**Comment by coryb** [comment]
Okay, if you have the code committed in a personal fork just point me at it, I can cherry pick the changes into master.  Otherwise I will wait for a PR.

btw, I just learned Jira comes with the websudo nonsense enabled by default making go-jira prompt constantly, so I am up for adding in a password option as well.  go-jira currently works with cookies to make auth work, but websudo ignores cookies when enabled, sigh.

**Comment by RC1140** [comment]
Pushed my changes here , https://github.com/Netflix-Skunkworks/go-jira/pull/49 , if you can have a look and suggest any changes that may be required for a merge and let me know what needs fixing.

**Comment by coryb** [comment]
worklog related commands were added a while ago, closing this issue.
