### ISSUE TITLE
Possible Bug - Watch flag w project: ... set only shows watched ticket in $project

### ISSUE THREAD

**Issue by colton22** [Netflix-Skunkworks/go-jira#183]
When project is not defined in ```~/.jira.d/config.yml```:
```
08:46:40 colton22:~ > cat ~/.jira.d/config.yml |grep project
08:47:17 colton22:~ > gojira list -w colton22
TEAM1-2659    In Progress C(2018-03-15) U(21 hours) Desc1
TEAM2-1759    Open        C(2018-01-03) U(89 days)  Desc2
TEAM2-1762    Open        C(2018-01-03) U(120 days) Desc3
```
When it is, it limits the projects searched. IMO this shouldn't happen unless we use trigger ```-p PROJECT```:
```
08:47:34 colton22:~ > echo 'project: TEAM1' >> ~/.jira.d/config.yml 
08:47:52 colton22:~ > gojira list -w colton22
TEAM1-2659 In Progress C(2018-03-15) U(21 hours) Desc1

08:47:55 colton22:~ > 
```

**Comment by colton22** [comment]
As an alternative, if this was the expected behavior we would have to create a custom query to specify all projects or request a ```-p all``` gets implimented, which could pose a problem to those who have project names ````ALL-[0-9]\{4\}```

**Comment by coryb** [comment]
This is by design.  I don't recommend adding `project: ...` configuration to your `$HOME/.jira.d/config.yml`.  I recommend adding `project: ...` to the `.jira.d/config.yml` in your project workspace.   This means `jira ls` will only show project related issues when you run that command in the same directory workspace as your project.  If you run `jira ls` in any other directory (ie your homedir) it will show all projects.

**Comment by colton22** [comment]
Nice; Didn't realize that! Thank you @coryb
