### ISSUE TITLE
ZSH Shell Completion is not working?

### ISSUE THREAD

**Issue by dmitry-saritasa** [Netflix-Skunkworks/go-jira#186]
I have added into ~/.zshrc

```
# jira CLI
eval "$(j --completion-script-zsh)"
```
and **j** points to jira-linux-amd64
```
~/Development/tools 
➜ ls -la $(which j)      
lrwxrwxrwx 1 root root 47 Jun  9 17:52 /usr/local/bin/j -> /home/dmitry/Development/tools/jira-linux-amd64
```
and [this](https://gist.github.com/dmitry-saritasa/6e0f15a438420b70a2621e2b08d9af5f) is my **~/.zshrc**

Any ideas what is wrong?

**Comment by coryb** [comment]
If you run the `jira --completion-script-zsh` above script you will see:
```
#compdef jira
autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit

_jira_bash_autocomplete() {
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$( ${COMP_WORDS[0]} --completion-bash ${COMP_WORDS[@]:1:$COMP_CWORD} )
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
complete -F _jira_bash_autocomplete jira
```
I think the last line is the relevent line, for autocomplete to work the command name need to be `jira`.  It will not work with your symlink because `j` does not trigger the autocomplete.

You can probably just manually copy/paste the above into your `.zshrc` directly and modify `jira` to `j` to get it to work.

**Comment by devstuff** [comment]
@dmitry-saritasa You could also modify your ~/.zshrc and add this line after the eval, so both the *jira* and *j* commands get autocomplete:
```
complete -F _jira_bash_autocomplete j
```
