### ISSUE TITLE
go-jira cannot be used as a library.

### ISSUE THREAD

**Issue by mikepea** [Netflix-Skunkworks/go-jira#19]
I'd like to use the core logic and API abstraction provided in go-jira to create an ncurses style JIRA browser, but AIUI the way it's written right now prevents this: CmdList et al produce output, rather than data.

I previously have made a branch that split the API requests and output logic, so this should be possible and relatively straightforward. Just wanted to check with you that this would be something you'd be interested in, before I whack together a reasonable sized PR.

**Comment by coryb** [comment]
Hey,

Yeah, I have been meaning to refactor the code a bit to allow it to be used a client library rather than just cli tool.  CmdList specifically has been already tweaked to call FindIssues and call a template with the results.  The output of most Cmd* funcs are almost entirely controlled with templates, but it probably makes sense to have the jira webservice logic to be in isolated routines and then the Cmd* funcs would just call the appropriate jira webservice routines.

I also want to tweak the layout of the project so that the code can more easily be imported as a golang library.  If you want to put together a PR to separate the jira webservice interactions from the template generation logic that would be great.  After I can merge that in I will move the code around so that `import "github.com/coryb/go-jira"` imports the `jira` package.  I have done this with a few other projects, but just have not gotten around to go-jira.

Thanks!
-Cory

**Comment by coryb** [comment]
Hey, it might make more sense for me to tweak the layout of the project before you play with refactoring it.  I could probably get it done in the next day or so, but if you have already started then it would probably complicate your PR/merge.

-Cory

**Comment by mikepea** [comment]
Nope, haven't started yet - prob will start in earnest after Xmas. So yep, if you can knock a branch together that reflects how you'd like it shaped, I can help out :)

**Comment by coryb** [comment]
Okay, I have moved the files around a bit to make it more like a conventional golang import library.  You would be able to use `import "github.com/Netflix-Skunkworks/go-jira"` and use the `jira` package in your golang project.   The change is 7268b9e, and pushed to master. 

To build it just use `make` and/or `make clean`.  I obviously need to add tests, but have not had a chance yet.

**Comment by mikepea** [comment]
Created https://github.com/Netflix-Skunkworks/go-jira/pull/22 to address my needs here.

**Comment by mikepea** [comment]
Closing this, cos I am using it as a library now!

Shameless plug @coryb --  https://github.com/mikepea/go-jira-ui
