### ISSUE TITLE
go-jira-1.0.18 is unable to log into Jira

### ISSUE THREAD

**Issue by williamh** [Netflix-Skunkworks/go-jira#198]
This is with go-jira 1.0.18 and a  private jira instance.
I have tried both with config.yml and without config.yml. Here is what my config.yml looks like:
endpoint: https://jira.domain.biz
user: me@domain.com
...

This seemed to start when I upgraded to 1.0.18 from 1.10.17, but when I downgraded again it didn't resolve.

Can you help?

Thanks,

William

**Comment by williamh** [comment]
I was also advised that nothing changed on our Jira instance yesterday.

**Comment by coryb** [comment]
I don't see anything in the changelog that would likely break you, and since you tested by reverting back to 1.0.17 and it still didn't work, I don't see how it could be caused from a code change.

So I am not sure what is going on.   What authentication configuration options to you use?  Do you use API tokens?  Do you use a `password-source` configuration option (ie use `pass` or keyring to get password)?

If you are using the session/cookie authentication perhaps there is an issue with your cookies file, try removing `$HOME/.jira.d/cookies.js` and logging in with `jira login`.  

There is a new `jira session` command which should help report if you have an active session (it will not attempt to login it, it will just report active sessions).

**Comment by artem-nefedov** [comment]
Can confirm that the same is happening to me.
Removing cookie file does not help.
Calling `jira login` reports "OK Found session for username", but afterwards it just asks for password again, and `-vvv` output shows "You are not authenticated".

**Comment by williamh** [comment]
After reverting to 1.0.17 and removing cookies.js. I was able to log in successfully.
The step I missed yesterday was removing cookies.js.

**Comment by coryb** [comment]
I no longer have an environment to easily test this code, my work and my test site both use api tokens now.  I will try to setup a local jira instance to see if I can use it for testing, I dont have any idea what is happening at the moment.

**Comment by coryb** [comment]
I have [released](https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.19) a new version, which I think addresses this issue.  It seems there was a subtle change in some of the dependencies that broke some logic replaying requests post-login.  Please give it a try, hopefully it will fix your issues.

**Comment by artem-nefedov** [comment]
For me, the new version works, but it asks for password every time, even though the cookie file is created.
With `-vvv` it always says "You are not authenticated", if I enter password it proceeds to work as normal. Removing cookie file manually does not help.

**Comment by coryb** [comment]
Okay, thanks for feedback, I will see if I can reproduce this issue and see why cookies might not be stored/resent correctly.

**Comment by coryb** [comment]
Opened a new issue #201 for the cookies-no-working issue.

**Comment by coryb** [comment]
I have [released](https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.20) another version to fix a regression with cookies cached on disk not being applied to subsequent requests.

**Comment by predatorian3** [comment]
Thank you @coryb for always be quick to respond and help out. v1.0.20 works for me as well so far for everything I do.
