### ISSUE TITLE
Pagination on Search/List

### ISSUE THREAD

**Issue by Techcadia** [Netflix-Skunkworks/go-jira#211]
in late 2017 Atlassian made a change that mandated a limit of 100 results and returned a pagination result in the json.
https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#pagination

Currently the start the `start_at` can't be controlled which would allow for a work around.

I was going to try to fix this with a PR but currently I am blocked by https://github.com/Netflix-Skunkworks/go-jira/issues/210

**Comment by mhite** [comment]
Getting pagination would be fantastic.

**Comment by burningalchemist** [comment]
Hi @Techcadia ,

Did you have any success with the issue in the end? Just curious.

Kind regards,
Sergei

**Comment by justmiles** [comment]
I [took a stab at this](https://github.com/Netflix-Skunkworks/go-jira/compare/master...justmiles:211). 
I noticed that if the results include too much data (IDK how much is too much) it throws the following error when writing output:

> ERROR Invalid Usage: yaml: control characters are not allowed

I image this is because all the results are stored in a buffer before writing the output and that buffer can only hold so much data. I ended up using this to export our entire Jira account, but had to export each project individually because of the amount of data. 

I'm not the strongest Go developer so while this works, it may not be the best approach. Any feedback is appreciated.

**Comment by Techcadia** [comment]
@justmiles Create a PR. A glance over the code it looks good the only thing that sticks out is that the `defer resp.Body.Close()` should be moved to the bottom of the loop and converted to `resp.Body.Close()`

https://blog.learngoprogramming.com/gotchas-of-defer-in-go-1-8d070894cb01
For more info on the reasoning.

**Comment by justmiles** [comment]
Thanks for the feedback. I moved `resp.Body.Close()` to the bottom of the loop as you suggested and opened PR #245.
