### ISSUE TITLE
how to set jira path

### ISSUE THREAD

**Issue by albasili** [Netflix-Skunkworks/go-jira#225]
This might be quite dumb, but I need to add a path to my endpoint, something like: ```https://jira.mydomain.com/jira```

Without it I will receive a ```301``` back.
Any idea?

**Comment by schnoddelbotz** [comment]
Doesn't setting ...
```yaml
endpoint: https://jira.mydomain.com/jira
```
... in `~/.jira.d/config.yml` work?

**Comment by albasili** [comment]
I get this:

`
ERROR JSON Parse Error: invalid character '<' looking for beginning of value from "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>301 Moved Permanently</title>\n</head><body>\n<h1>Moved Permanently</h1>\n<p>The document has moved <a href=\"https://jira.melexis.com/jirarest/auth/1/session\">here</a>.</p>\n<hr>\n<address>Apache/2.2.22 (Debian) Server at jira.melexis.com Port 443</address>\n</body></html>\n"
`

**Comment by schnoddelbotz** [comment]
Hm. Looks like you get redirected to the login page... that's indeed a bit weird...

(at)coryb could possibly quickly confirm that this is due to your 5+ years old Jira release ( https://confluence.atlassian.com/jira/jira-6-1-3-release-notes-423625278.html ); I can only guess that it's the issue, as go-jira tests are using 7.2.0 ( https://github.com/Netflix-Skunkworks/go-jira/blob/master/t/dockerroot/jiratestservice/pom.xml ) and go-jira itself exists for 4 years only.

Try pinging him from within this issue if in doubt, but I'd guess you're out of luck until you update.
Maybe `jira login -vvv` also helps you to track this further down: How does the first request URI that triggers the redirect look like? Mine (after previously explicitly logging out):
```
...
DEBUG Request 1: GET /rest/auth/1/session HTTP/1.1
Accept: application/json
...
DEBUG Response 1: HTTP/1.1 401
Content-Type: application/json;charset=UTF-8 (in all responses!)
...
DEBUG Request 1: POST /rest/auth/1/session HTTP/1.1
...
DEBUG Response 1: HTTP/1.1 200
...
DEBUG Request 1: GET /rest/auth/1/session HTTP/1.1
...
DEBUG Response 1: HTTP/1.1 200 
```

**Comment by schnoddelbotz** [comment]
Just to confirm: setting the `endpoint:` with a trailing `/foobar` in config.yml leads to requests like:
```
DEBUG Request 1: GET /foobar/rest/auth/1/session HTTP/1.1
```
So in general, it should work with a non-standard path (it leads to 404 for me; our setup is using `/`).

**Comment by albasili** [comment]
> So in general, it should work with a non-standard path (it leads to 404 for me; our setup is using /).

what do you mean by that?

**Comment by albasili** [comment]
thanks for your insights, I'll close the issue.
