### ISSUE TITLE
FTBFS with go go1.10.3 gccgo (SUSE Linux) 8.2.1 20181108

### ISSUE THREAD

**Issue by mcepl** [Netflix-Skunkworks/go-jira#229]
```
matej@stitny: ~$ go get gopkg.in/Netflix-Skunkworks/go-jira.v1/cmd/jira
# gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/github.com/coryb/figtree
In function ‘figtree.NewComplex64Option’:
go1: note: the ABI of passing structure with complex float member has changed in GCC 4.4
# gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd
.go/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd/componentAdd.go:55:6: error: ‘resp’ declared and not used
  var resp *jiradata.Component
      ^
matej@stitny: ~$ go version
go version go1.10.3 gccgo (SUSE Linux) 8.2.1 20181108 [gcc-8-branch revision 265914] linux/amd64
matej@stitny: ~$
```
What I am missing?

**Comment by schnoddelbotz** [comment]
Interesting. But I'm not sure whether go-jira is the place to report this issue as this seems to be related to gccgo -- because the standard go compiler does not complain about the code section in question, as resp is used inside the closure:
```go
  var resp *jiradata.Component
  err = jiracli.EditLoop(&opts.CommonOptions, &opts.Component, component, func() error {
    resp, err = jira.CreateComponent(o, globals.Endpoint.Value, component)
    return err
  })
```
Looking at https://stackoverflow.com/questions/19957323/go-closure-variable-scope I believe the standard go compiler is working as intended, while gccgo isn't.

Accordingly, to fix your issue at hand, I'd use https://golang.org/doc/install -- or the SUSE go package https://build.opensuse.org/package/show/openSUSE:Factory/go1.11 (?) instead of https://golang.org/doc/install/gccgo ... and close the issue here and discuss further on gccgo issue tracker.

**Comment by mcepl** [comment]
You are right, just for other openSUSE users: ``sudo update-alternatives --config go`` allows switching between different implementations of go.
