### ISSUE TITLE
jira.exe unable to read %HOME%\.jira.d\config.yml

### ISSUE THREAD

**Issue by predatorian3** [Netflix-Skunkworks/go-jira#41]
I seem to be having an issue where the `jira.exe` executable is unable to find the `%HOME%\.jira.d\config.yml` file. 

```
C:\Users\user01\Downloads
λ jira-windows-amd64.exe
2016-04-22T17:36:08.031-05:00 ERROR [main.go:270] endpoint option required.  Either use --endpoint or set a endpoint option in your ~/.jira.d/config.yml file
```

I have created the `%HOME%\.jira.d\config.yml` and at least put `endpoint:` in there.  When I specify the command line arguments, it works as expected. 

I am using Windows 7 with Go 1.6
```
C:\Users\user01
λ go version
go version go1.6 windows/amd64
```

**Comment by coryb** [comment]
Hey, sorry I missed this issue.

Unfortunately I don't have access to any Windows machines to test on, I have only tested on OSX and Linux.  It is probably something stupid with os path separators, but I have no way currently to verify.   If you feel up to it I'd love a pull request, otherwise I will try to reproduce when I get access to a Windows environment.

-Cory

**Comment by predatorian3** [comment]
I'm still working my way through GO and learning the language, then I'll take a stab at it.

**Comment by coryb** [comment]
Hey, in the last few days I have been able to set up a vagrant VM with windows 2012, so I have started playing with it and fixing `go-jira`.  The current plan is to just use the USERPROFILE environment variable to find the homedir and look for `.jira.d\config.yml` in there.  So I will probably have something moderately functional in next few days, but I encourage you to keep learning Go anyway :)

-Cory

**Comment by coryb** [comment]
Hey @predatorian3, I have just created a new release with some fixes for Windows:
https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v0.1.1

Try out the latest binary and see if it works better for you.  The config will be located at %USERPROFILE% instead of %HOME% and should look something like:
```
> type %USERPROFILE%\.jira.d\config.yml
endpoint: https://jira
```

**Comment by predatorian3** [comment]
Roger that, testing now.

**Comment by predatorian3** [comment]
So far so good. I'm able to list my Jiras and queries against them. So far, the issue seems to be resolved. Thank you for your hard work @coryb

**Comment by coryb** [comment]
Excellent, thanks for checking it out.  Closing issue.
