### ISSUE TITLE
Not possible to itterate over the issuetype field when creating a ticket

### ISSUE THREAD

**Issue by jamime** [Netflix-Skunkworks/go-jira#79]
It's not possible to display all of the available issue types in the create issue template as it defaults to Bug/Task. I would like to be able to display the options just like how components are displayed.

**Comment by coryb** [comment]
Hey sorry, I am not quite understanding the problem.  There is an `issuetypes` command to list the various issuetypes for your project.
```
$ jira issuetypes --project BASIC
Improvement:  An improvement or enhancement to an existing feature or task.
Task:         A task that needs to be done.
Sub-task:     The sub-task of the issue
New Feature:  A new feature of the product, which has yet to be developed.
Bug:          jira.translation.issuetype.bug.name.desc
Epic:         A big user story that needs to be broken down. Created by JIRA Software - do not edit or delete.
```

Then you can create an issue with the specified issuetype:
```
jira create --project BASIC --issuetype Sub-task
```
-Cory

**Comment by jamime** [comment]
By default the following template itterates all of the possible components and displays them in your $EDITOR in a comment. I'd like to do the same with the available issuetype but because of the [default fallback](https://github.com/Netflix-Skunkworks/go-jira/blob/5de5a3f862d0aa6bff594f0d04179aedde342032/commands.go#L266) this is not possible as .meta.fields.issuetypes.allowsValues will only contain the fallback issue type. `jira issuetypes` still gives all available issue types.

````
components: # Values: {{ range .meta.fields.components.allowedValues }}{{.name}}, {{end}}{{if .overrides.components }}{{ range (split "," .overrides.components)}}
    - name: {{.}}{{end}}{{else}}{{ range .fields.components }}
    - name: {{ .name }}{{end}}{{end}}
````

**Comment by coryb** [comment]
It is a bit hard to describe, but I think this is a limitation in Jira.  The `.meta` available for the create template is only available because you must pre-select an issue type.  I cannot ask Jira to give me a list of fields that go into a create template without first specifying an issueType.  If we were able to manufacture a list of issueTypes to be presented in the create template then it would not work reliably because we would effectively have to re-render the template based on what issueType the user wants, which is currently impossible given how `go-jira` is current written.  The only thing that I can think of that might get close to what you want would be to first prompt the user to pick the issueType in some selection menu, then after the selection generate the create template to edit.

**Comment by jamime** [comment]
Thanks for explaining the limitation.
