### ISSUE TITLE
'Pass' authentication asks for passwords for every command

### ISSUE THREAD

**Issue by petewilcock** [Netflix-Skunkworks/go-jira#84]
I've set up `pass` as an authentication method, and use `jira login` which asks for a password and appears to work. 

Then I do `jira list` and it asks for a password again... and for every command. The command works when I enter the password but asks every single time. Not sure what I've done wrong as I've followed every step in the README for the set-up for this. Any ideas?

**Comment by coryb** [comment]
Hmm, not sure.  First double check that your `$HOME/.jira.d/config.yml` file has a config line like:
```
password-source: pass
```

Also what happens when you run:
```
pass GoJira/$USER
```

That should print your password to the console. It should prompt you periodically but repeatedly calling the `pass GoJira/$USER` command should only prompt the first time.

If the `config.yml` setting is in place and the `pass` command is working as expected I am not sure what else could be the issue.
