### ISSUE TITLE
Every command is a bad request

### ISSUE THREAD

**Issue by realmika** [Netflix-Skunkworks/go-jira#85]
I've added my config.yml and logged in correctly (if I use bad password I get error message, with good password I get _no_ message)

Now every command is like this:
```
jira ls

2017-06-23T13:08:55.405+02:00 ERROR [cli.go:243] response status: 400 Bad Request
2017-06-23T13:08:55.405+02:00 ERROR [util.go:234] Field 'resolution' does not exist or this field cannot be viewed by anonymous users.
2017-06-23T13:08:55.405+02:00 ERROR [util.go:234] The value 'WAPPIA' does not exist for the field 'project'.
2017-06-23T13:08:55.405+02:00 ERROR [util.go:234] Not able to sort using field 'priority'.
```

I am 100% sure that `WAPPIA` is a correct project name. Any pointers please? Thanks!

**Comment by coryb** [comment]
The problem you are describing is how Jira deals with unauthenticated requests.  It returns 400's instead of 403's.  The default authentication method that go-jira uses is cached session cookies, but this no longer works with Jira hosted on atlassian.net or the default configuration for Jira installs.  It now requires either integration with your os's password keychain (on OSX) or using a tool call "pass" for Linux and OSX.  Sadly I have not found one to work Windows yet, so not sure if this is a problem for you.  You can read more about the authenticaion solutions here:
https://github.com/Netflix-Skunkworks/go-jira#authentication

Hope this helps.
-Cory

**Comment by realmika** [comment]
Ah Awesome man, I got it going! :)

On Ubuntu I couldn't get the keychain going, but pass worked out. Script for remembering the password seems to be outdated, env-file is deprecated, but I'm fine typing it in once a day.

Thanks for the help!
